component_depth: 1
languages:
- name: typscript
  production:
    exclude:
      - /GradeAchiever/src/models/__mocks__/.*
      - /GradeAchiever/src/__tests__/.*
  test:
    include:
      - /GradeAchiever/src/__tests__/.*
