component_depth: 1
languages:
- name: typscript
  production:
    exclude:
      - /GradeAchiever/src/models/\_\_mocks\_\_/.*
      - /GradeAchiever/src/\_\_tests\_\_/.*
  test:
    include:
      - /GradeAchiever/src/\_\_tests\_\_/.*
