language: node_js
node_js:
  - "node"

services:
  - docker

before_install:
  - docker build -t grade-achiever ./GradeAchiever
  

install:
  - npm --prefix ./GradeAchiever install

script:
  - npm --prefix ./GradeAchiever run sample-script
  - npm link typescript
  - tsc -v
  - tslint -v
  - npm --prefix ./GradeAchiever run test
  - tslint -p ./GradeAchiever --test
