language: node_js
node_js:
  - "node"

services:
  - docker

before_install:
  - docker build -t grade-achiever ./GradeAchiever
  

install:
  - npm --prefix ./GradeAchiever install
  - npm --prefix ./GradeAchiever install -g typescript
  

script:
  - tsc -v
  - tslint -v
  - npm --prefix ./GradeAchiever run test
  - tslint -p ./GradeAchiever --test
