language: node_js
dist: trusty
sudo: required
node_js:
  - "node"
env:
  - LHCI_GITHUB_TOKEN=438c389b7b70399e97ad252b55b04b84d2e7166c
services:
  - docker

before_install:

  #- tsc -p ./GradeAchiever/
  #- docker build -t grade-achiever ./GradeAchiever
  - docker-compose -f ./GradeAchiever/docker-compose.yml build
  - docker-compose -f ./GradeAchiever/docker-compose.yml up -d
  - sleep 10
install:
  - npm --prefix ./GradeAchiever install

script:
  - npm --prefix ./GradeAchiever run tslint-test
  - lhci autorun
  - npm --prefix ./GradeAchiever run compile
  - npm --prefix ./GradeAchiever run test
after_script:
  - docker-compose -f ./GradeAchiever/docker-compose.yml down
