language: node_js
node_js:
  - "node"
env:
  - LHCI_GITHUB_TOKEN=438c389b7b70399e97ad252b55b04b84d2e7166c
services:
  - docker

before_install:
  - npm install -g @lhci/cli@0.3.x
  #- docker build -t grade-achiever ./GradeAchiever
  - docker-compose -f ./GradeAchiever/docker-compose.yml build
install:
  - npm --prefix ./GradeAchiever install

script:
  - npm --prefix ./GradeAchiever run tslint-test
  - docker-compose -f ./GradeAchiever/docker-compose.yml up &
  - lhci collect --url="http://localhost:8080" --config=./.lighthouserc.json 
  - npm --prefix ./GradeAchiever run compile
  - npm --prefix ./GradeAchiever run test
  - docker-compose -f ./GradeAchiever/docker-compose.yml kill
