language: node_js
node_js:
  - "node"

services:
  - docker

before_install:
  - docker build -t grade-achiever ./GradeAchiever
  

install:
  - npm --prefix ./GradeAchiever install
  - npm install -g gulp
  # ^ this is the code that works?
  #- npm install --save-dev gulp-tslint

script:
  - npm --prefix ./GradeAchiever run test
  - gulp tslint
